[5:27 PM] Lydia Ingabire (Unverified)
name: Continuous Integration
 
on:
  push:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install dependencies
        run: yarn add
 
      - name: Run tests
        run: yarn run test
 
  test-on-macos:
    runs-on: window-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install dependencies
        run: yarn add
 
      - name: Run tests on macOS
        run: yarn run test